name: Build on Tag

on:
  workflow_dispatch:

jobs:

  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ${GITHUB_WORKSPACE}/build_kernel.sh
         bash ${GITHUB_WORKSPACE}/build_kernel.sh
      shell: bash
    - name: Save Artifact
      uses: actions/upload-artifact@v4
      with:
          name: Image.gz
          path: out/arch/arm64/Image.gz

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
          to: -1002075366867
          token: 6504843621:AAFgBLfZk5vkyNlATqeVuSs46VkYXIlwJew
          message: Image file!, took ${{ steps.out.outputs.elapsed_time_ }} seconds.
          document: out/arch/arm64/boot/Image.gz
