name: Build Kernel Telegram

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Checkout zipper
      uses: actions/checkout@v3
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Give Permissions
      run: |
            git config --global --add safe.directory '/github/workspace/'
            chmod +x '/github/workspace/toolchain/*'

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Varoo Kernel
      with:
        arch: arm64
        compiler: gcc/12
        defconfig: physwizz_defconfig
        image: Image.gz
    - name: tar boot folder
      id: out
      run: |
        start_time_="$(date +%s)"
        date="$(date +%d%m%Y-%I%M)"
        pwd
        ls
        tar -cf boot.tar out/arch/arm64/boot/Image.gz
        ls
        cd out/arch/arm64/boot/
        pwd
        ls
        cd
        #set_output outfile_ $GITHUB_WORKSPACE/boot.tar
        #set_output elapsed_time_ "$(echo "$(date +%s)"-"$start_time_" | bc)"
    - name: Send to TG
      uses: appleboy/telegram-action@master
      with:
          to: -1002075366867
          token: 6504843621:AAFgBLfZk5vkyNlATqeVuSs46VkYXIlwJew
          message: Image file!, took ${{ steps.out.outputs.elapsed_time_ }} seconds.
          document: $GITHUB_WORKSPACE/out/arch/arm64/boot/Image.gz
      
    - name: Release build
      uses: appleboy/telegram-action@master
      with:
        to: -1002075366867
        token: 6504843621:AAFgBLfZk5vkyNlATqeVuSs46VkYXIlwJew
        message: Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.
        document: ${{ steps.build.outputs.outfile }}
